# Generated by Django 5.1.6 on 2025-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(max_length=255),
        ),
    ]
