# Generated by Django 5.1.6 on 2025-03-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone_number', models.CharField(max_length=15, unique=True)),
                ('type_client', models.BooleanField(default=False)),
                ('report_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
