# Generated by Django 5.1.6 on 2025-03-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_clients',
            field=models.CharField(default='individual', max_length=255),
        ),
    ]
