# Generated by Django 5.1.6 on 2025-02-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_tax',
            field=models.DateField(blank=True, null=True),
        ),
    ]
