# Generated by Django 5.1.6 on 2025-02-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='static/reports/'),
        ),
    ]
